### ISSUE TITLE
Probleme de scroll [mobile ver.]

### ISSUE THREAD

**Issue by mathieu-ui** [TchoupiGang/EDT-Prague#1]
Dans la version mobile du site, on doit scroller deux fois pour atteindre la fin de la page. 

> On doit scroller une fois sur le planning, et atteindre le bas du planning, pour pouvoir scroller sur la page ;)

**Comment by thomasedel** [comment]
C'est **aberrant**
Je propose de rendre la barre de navigation **sticky**
